#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

workspace 'MLKitExample.xcworkspace'

target 'MLKitExample' do
	project 'MLKitExample.xcodeproj'
	
	pod 'MLKit', :path => '../MLKit.podspec'
#    pod 'MLRefreshControl', '~> 0.0.3'
    pod 'MLRefreshControl', :path => '~/MLProjects/MLRefreshControl'
end
