source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

workspace 'MLKitExample.xcworkspace'

target 'MLKitExample' do
	project 'MLKitExample.xcodeproj'
    
    pod 'MLProgressHUD', '~>1.0.5'
    pod 'MLKit', :path => '../MLKit.podspec'
#    pod 'MLLayout', :path => '~/MLProjects/MLLayout'
end
